# Generated by Django 4.2.5 on 2023-09-06 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=12)),
                ('nome_empresa', models.CharField(max_length=150)),
                ('categoria_empresa', models.CharField(max_length=50)),
                ('quitado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FINECAP.reserva')),
            ],
        ),
    ]
